[package]
name = "discrete_fourier_transform_by_hand" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["B <b@example.com>"]

[dependencies]
num = "0.4"
float-cmp = "*"
