cargo-features = ["edition2021"]
[package]
name = "lockfree_vector"
version = "0.1.0"
edition = "2021"
[lib]
name = "lockfree_vec_lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
